### ISSUE TITLE
Music files + Website

### ISSUE THREAD

**Issue by Versiris** [katstasaph/otii#1]
Just found this project and wow!! Excellent work! I'm wondering if you could upload the music files, I've been looking to remaster the soundtrack but I can't figure out how to extract them.

**Comment by Versiris** [comment]
Just adding to this: I made a little mini-site incorporating the data you compiled: https://oregontrailtips.carrd.co/
I'd be happy to keep updating it as this project continues! Apologies for commenting here, I couldn't find another way of contact.

**Comment by katstasaph** [comment]
Hi, no need to apologize at all, totally fine! This looks really cool and is definitely a much more presentable format than the ones I have.

As far as the music files I also haven't figured out how to extract them (although, to be fair, I haven't really been trying). There are audio rips on YouTube including the tracks that as far as I know aren't played in-game. The composer Eric Speier also has some of them [on his website](https://www.filmmusic.org/#playlist) (bottom left). That might be the best there is at the moment, unfortunately...

**Comment by Versiris** [comment]
Thank you! I did find your rips of the unused songs which is what led me to find your project. If you had any advice on how one would best go about ripping them myself even just stereo mix .wav recording that would be amazing. I'm still learning how to fiddle with code stuff but wanted to get a clean rip of the game music to make a remastered soundtrack out of. If you have any tips or find anything in the future please do let me know! I'm happy to hear someone else is passionate about the game!

**Comment by Zott820** [comment]
The Oregon Trail II CD has 3 tracks in Red Book audio that are higher quality than the in-game versions. 
Example: https://youtu.be/ngp1pq7IetU

 @Versiris , I can send those along to you if you'd like.

Kind of surprised Eric Speier did not use the high resolution version as the demo on his website. :O

**Comment by Versiris** [comment]
Huh, interesting, I had no idea a few of the tracks were on CD like that! They really could have released a soundtrack CD even with "best of" on it, I certainly would have bought a copy. @Zott820 that would be amazing if you could pass those along. If it's easier for you my email / contact information is in my profile. Cheers!

**Comment by katstasaph** [comment]
no worries! (You may or may not have seen this, apologies if I'm repeating myself, but the spreadsheet isn't up to date, and a lot of info hasn't been added that is in the annotated code here. Locations and health data, in particular, are lagging a lot on the spreadsheet.)

**Comment by Versiris** [comment]
Oops I didn't know that!! I'll check out the actual code! 👀

**Comment by Versiris** [comment]
@katstasaph Hey again! Do you happen to have the rips you posted on YouTube of the unused music? A friend of mine and I were trying to fiddle with the code to figure out how to find these but we gave up... Would love to just have the recordings even if it's not the raw midi or whatnot.
